### ISSUE TITLE
please include working example

### ISSUE THREAD

**Issue by petigura** [lukehandley/ttp#4]
I needed 

`realtesting.py`,` realtest.csv`

- plotly, (conda)
- numpy, (conda)
- astropy, (conda)
- pandas (conda)
- matplotlib (conda)

- gurobipy (pip)
- astroplan (pip)

Then failed at the gurobi license part

**Comment by jluby127** [comment]
added a tutorial within the addAnimationPlot branch and updated readme with instructions
