### ISSUE TITLE
Add wrap limit as plotting parameter

### ISSUE THREAD

**Issue by lukehandley** [lukehandley/ttp#5]
The 2D plots of the telescope path should have some indication of the wrap limit to make it clear when there are wrap unwinds. This could be either a line drawn on the plot at the wrap angle, or a shift in coordinates so that the wrap is placed at the top/bottom of the plot.

**Comment by jluby127** [comment]
Luke added this in lukedev which was merged to addPriority and then into main. Jack may make aesthetic changes in future
