### ISSUE TITLE
Objective Scaling and Optimality Gap

### ISSUE THREAD

**Issue by lukehandley** [lukehandley/ttp#6]
We should discuss the scaling of different terms in the objective (i.e., the units of slew time). Ideally, the objective score would be interpretable to one of us, and it should be easily explained to others. 

This will guide our discussion about the right way for users to specify optimality gap (perhaps a time in minutes from optimal?). We can then include this as a 'statistic' for the solved model. In principle we can get all this information from the model + objective score if we scale it in natural units.

## For example:

Observations:
Obs Requested: 30
Obs Scheduled: 25
Best Bound: 28

Slews:
Discretized Slew Time: 10 minutes
Real Slew Time : 12 minutes
Best Bound: 9 minutes

**Comment by jluby127** [comment]
fixed in the sense that we are no longer reporting these best bound numbers because including priorities throws off this calculation irreparably
