### ISSUE TITLE
Resolve exposure time for multi-exposure targets

### ISSUE THREAD

**Issue by lukehandley** [lukehandley/ttp#7]
Lets agree on a formula for computing the effective visit time of a target which has multiple consecutive exposures. This can either occur internally for each star object, or a blanket function applied to every star in the model.

 I think @jluby127 will already have a version of this for plotting, but it also needs to be considered during the data ingestion stage to get the exposure times right.

This might even be relevant for single exposure targets which have exposure times of a similar or less magnitude to the readout time.

**Comment by jluby127** [comment]
this is fixed in addPriority branch
